#!/bin/sh
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

SORT='' #name
PAGE=1
SEARCH=""
REVERSE=""
DOMAIN="https://www.1337xx.to"
DELIM="\t"

C_LE="31"
C_SE="32"
C_SIZE="33"
C_AUTHOR="35"
C_TIME="36"
C_NAME="39"
COLOR=1

alias ucurl='curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36" -H "Accept-Encoding: gzip, deflate" --compressed'

while [ $# -gt 0 ]
do
  case "$1" in
    -s|--sort)
      case "$2" in
        name) SORT='';;
        size) SORT='size';;
        time) SORT='time';;
        se) SORT='seeers';;
        le) SORT='leechers';;
      esac
      shift;;
    -h|--help)
        NAME="$(basename "$0")"
        printf "%s [OPTION]... [PATTERN]\nSearch for PATTERN in 1337x.\nExample: %s -s size -p 2 'archlinux'\n\n" "$NAME" "$NAME"
        printf "Options:\n  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, time, se, le\n"
        printf "  -r,  --reverse\t\tsort in reverse\n"
        printf "  -d,  --domain DOMAIN\t\tset domain to DOMAIN\n"
        printf "  -D,  --delimiter DELIM\tset delimiter to DELIM\n"
        printf "  -p,  --page NUM\t\tshow page at NUM\n"
        printf "  -c,  --color\t\t\tcolor output\n"
        printf "  -C,  --no-color\t\tdisable coloring of output\n"
        printf "  -h,  --help\t\t\tshow help\n"
        printf "\nMagnet link will be copied via xclip.\n"
        exit 0;;
    -c|--color)
        COLOR=1;;
    -C|--no-color)
        COLOR=0;;
    -r|--reverse)
        REVERSE="1";;
    -d|--domain)
        DOMAIN="$2"
        shift;;
    -p|--page)
        PAGE="$2"
        shift;;
    -D|--delimiter)
        DELIM="$2"
        shift;;
    *)
        if [ -z "$SEARCH" ]
        then
          SEARCH="$1"
        else
          SEARCH="$SEARCH $1"
        fi;;
  esac
  shift
done

SEARCHP=$(echo "$SEARCH" | tr ' -+/_:;' '.')

if [ -n "$SORT" ]
then
    PSORT="sort-search"
    [ -z "$REVERSE" ] && RSORT="desc" || RSORT="asc"
else
    RSORT=""
    PSORT="search"
fi

t1="$(ucurl -s "$DOMAIN/$PSORT/$SEARCHP/$SORT/$RSORT/$PAGE/" | hgrep 'tbody')"
links="$(echo "$t1" | hgrep 'a +href="/torrent/.*" @p"'$DOMAIN'/%(href)a\n"')" #links
{
echo "$t1" | hgrep 'a +href="/torrent/.*" @p"%i\n"' #name
echo "$t1" | hgrep 'td +class="coll-date" @p"%i\n"' #time
echo "$t1" | hgrep 'td +class="coll-4 .*" @p"%i\n"' | grep -o '^[^<]*' #size
echo "$t1" | hgrep 'td +class="coll-2 seeds" @p"%i\n"' #se
echo "$t1" | hgrep 'td +class="coll-3 leeches" @p"%i\n"' #le
echo "$t1" | hgrep 'td +class="coll-5 .*"; a @p"%i\n"' #uploader
} | awk 'function print_fields(lines,fields,step) {
        colors[0] = '"$C_NAME"'
        colors[1] = '"$C_TIME"'
        colors[2] = '"$C_SIZE"'
        colors[3] = '"$C_SE"'
        colors[4] = '"$C_LE"'
        colors[5] = '"$C_AUTHOR"'
        ORS = ""
        for (i = 0; i < step; i++) {
            for (j = 0; j < fields; j++) {
                if (j != 0)
                    print "'"$DELIM"'"
                if ('"$COLOR"')
                    print "\033["colors[j]"m"lines[(step*j)+i]"\033[0m"
                else
                    print lines[(step*j)+i]
            }
            printf "\n"
        }
    }

    BEGIN { l=0; fields = 6 }
    { lines[l++]=$0 }
    END {
        if (l >= fields)
        if (l%fields == 0) {
                step = l/fields
                print_fields(lines,fields,step)
        } else
            print "length of some data fields does not match the others"
    }' | nl

[ -z "$links" ] && exit 1
printf 'num> '
read -r NUMBER
[ "$NUMBER" -gt 0 ] && ucurl -g -s "$(echo "$links" | sed "${NUMBER}q;d")" | grep -oE -m 1 'magnet:\?[^"]+' | tee /dev/stderr | tr -d '\n' | xclip -sel clip
