#!/bin/sh
# by TUVIMEN <suchora.dominik7@gmail.com>
# License: GNU GPLv3

by_name=""
by_time="time"
by_size="size"
by_se="seeders"
by_le="leechers"

SORT="$by_name"
PAGE=1
SEARCH=""
REVERSE=""
DOMAIN="https://www.1337xx.to"
DELIM="\t"

C_LE="31"
C_SE="32"
C_SIZE="33"
C_AUTHOR="35"
C_TIME="36"
C_NAME="39"
COLOR=1

while [ $# -gt 0 ]
do
  case "$1" in
    -s|--sort)
      case "$2" in
        name) SORT="$by_name";;
        size) SORT="$by_size";;
        time) SORT="$by_time";;
        se) SORT="$by_se";;
        le) SORT="$by_le";;
      esac
      shift;;
    -h|--help)
        NAME="$(basename "$0")"
        printf "%s [OPTION]... [PATTERN]\nSearch for PATTERN in 1337x.\nExample: %s -s size -p 2 'archlinux'\n\n" "$NAME" "$NAME"
        printf "Options:\n  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, time, se, le\n"
        printf "  -r,  --reverse\t\tsort in reverse\n"
        printf "  -d,  --domain DOMAIN\t\tset domain to DOMAIN\n"
        printf "  -D,  --delimiter DELIM\tset delimiter to DELIM\n"
        printf "  -p,  --page NUM\t\tshow page at NUM\n"
        printf "  -c,  --color\t\t\tcolor output\n"
        printf "  -C,  --no-color\t\tdisable coloring of output\n"
        printf "  -h,  --help\t\t\tshow help\n"
        printf "\nMagnet link will be copied via xclip.\n"
        exit 0;;
    -c|--color)
        COLOR=1;;
    -C|--no-color)
        COLOR=0;;
    -r|--reverse)
        REVERSE="1";;
    -d|--domain)
        DOMAIN="$2"
        shift;;
    -p|--page)
        PAGE="$2"
        shift;;
    -D|--delimiter)
        DELIM="$2"
        shift;;
    *)
      SEARCH="$1"
  esac
  shift
done

SEARCHP=$(echo "$SEARCH" | tr ' -+/_:;' '.')

t1="$(mktemp)"
t_time="$(mktemp)"
t_size="$(mktemp)"
t_se="$(mktemp)"
t_le="$(mktemp)"
t_name="$(mktemp)"
t_link="$(mktemp)"
t_uploader="$(mktemp)"
trap 'rm "$t1" "$t_name" "$t_link" "$t_se" "$t_le" "$t_time" "$t_size" "$t_uploader"' EXIT

if [ -n "$SORT" ]
then
    PSORT="search-sort"
    [ -z "$REVERSE" ] && RSORT="desc" || RSORT="asc"
else
    RSORT=""
    PSORT="search"
fi

curl -s "$DOMAIN/$PSORT/$SEARCHP/$SORT/$RSORT/$PAGE/" | hgrep 'tbody' > "$t1"
hgrep 'a +href="/torrent/.*" @p"%i\n"' "$t1" > "$t_name"
hgrep 'a +href="/torrent/.*" @p"'$DOMAIN'/%(href)a\n"' "$t1" > "$t_link"
hgrep 'td +class="coll-2 seeds" @p"%i\n"' "$t1" > "$t_se"
hgrep 'td +class="coll-3 leeches" @p"%i\n"' "$t1" > "$t_le"
hgrep 'td +class="coll-date" @p"%i\n"' "$t1" > "$t_time"
hgrep 'td +class="coll-4 .*" @p"%i\n"' "$t1" | grep -o '^[^<]*' > "$t_size"
hgrep 'td +class="coll-5 .*"; a @p"%i\n"' "$t1" > "$t_uploader"

color_lines() {
    sed "s/^/\x1b[$1m/; s/$/\x1b[0m/" "$2" > "$3"
    cp "$3" "$2"
}

if [ "$COLOR" -eq 1 ]
then
    color_lines "$C_SIZE" "$t_size" "$t1"
    color_lines "$C_NAME" "$t_name" "$t1"
    color_lines "$C_LE" "$t_le" "$t1"
    color_lines "$C_SE" "$t_se" "$t1"
    color_lines "$C_AUTHOR" "$t_uploader" "$t1"
    color_lines "$C_TIME" "$t_time" "$t1"
fi

paste -d "$DELIM" "$t_name" "$t_time" "$t_size" "$t_se" "$t_le" "$t_uploader" | nl
printf 'num> '
read -r NUMBER
[ "$NUMBER" -gt 0 ] && curl -g -s "$(sed "${NUMBER}q;d" "$t_link")" | grep -oE -m 1 'magnet:\?[^"]+' | tee /dev/stderr | tr -d '\n' | xclip -sel clip
